name: 🚀 New feature proposal

description: Propose a new feature to be added to pinos-ui

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature report!

  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: "Clear and concise description of the problem. Please make the reason and usecases as detailed as possible. If you intend to submit a PR for this issue, tell us in the description. Thanks!"
      placeholder: As a developer using pinos-ui I want [goal / wish] so that [benefit].
    validations:
      required: true
